# Generated by Django 4.2.11 on 2025-07-01 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="related_category",
            field=models.ManyToManyField(
                blank=True, related_name="_related_products", to="store.category"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="store.category",
            ),
        ),
    ]
