version: "3.9"
services:
  db:
    image: postgres:16
    container_name: postgres-ppm
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Pietrolio19 #potrebbe essere postgres
      POSTGRES_PASSWORD: Pi&tro88
      POSTGRES_DB: ppm_db
    volumes:
      - ./db-data:/var/lib/postgresql/data